apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trading-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ruiyang01/trading-system.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: trading-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
