apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
  namespace: trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strategy-engine
  template:
    metadata:
      labels:
        app: strategy-engine
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: strategy-engine
          image: 491325670398.dkr.ecr.eu-central-1.amazonaws.com/trading-strategy-engine:d539a557c36bda9892e862522ce5cfcfe72969d3
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: LOG_LEVEL
              value: INFO
