apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  namespace: trading-system-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-fetcher
  template:
    metadata:
      labels:
        app: data-fetcher
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: data-fetcher
          image: 491325670398.dkr.ecr.eu-central-1.amazonaws.com/trading-data-fetcher:c3656c059d17f00ee84664b2bdba20d786a1b080
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: LOG_LEVEL
              value: INFO
