apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
  namespace: trading-system-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strategy-engine
  template:
    metadata:
      labels:
        app: strategy-engine
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: strategy-engine
          image: /trading-strategy-engine:c816936a41a127567460b3c6f83c279c100e8989
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: LOG_LEVEL
              value: INFO
